[package]
name = "token_deque"
version = "0.1.0"
authors = ["John VanEnk <vanenkj@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
proptest = "0.9"
rand = "0.7"